# Generated by Django 3.2.5 on 2021-07-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('accepted', 'Accepted')], max_length=10),
        ),
    ]
